import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from '@/app/Head'
import Sidebar from '@/components/Sidebar'
import SessionProvider from '@/components/SessionProvider'
import {getServerSession} from 'next-auth'
import {authOptions} from '@/pages/api/auth/[...nextauth]'
import Login from '@/components/Login'
import ClientProvider from '@/components/ClientProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="ja">
      <Head />
      <body className={inter.className}>
      <SessionProvider session={session}>
        {!session ? (
          <Login />
        ) : (
            <div className={"flex"}>
              {/* Sidebar */}
              <div className={"bg-[#202123] min-w-[10rem] min-h-screen overflow-y-auto md:min-w-[20rem]"}>
                <Sidebar />

              </div>

              {/* Client Provider - Notification */}
              <ClientProvider />

              <div className={"bg-[#343440] w-full"}>{children}</div>
            </div>
        )}
      </SessionProvider>

      </body>
    </html>
  )
}
